apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-music
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: spring-music
          image: <REGISTRY>/<ACR_REPO_NAME>
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          env:
            - name: REDIS
              value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: azure-vote-front